AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ExtractMeta:
    Properties:
      CodeUri: s3://proceso-deployments-8927459/931570c29f64b9176814bfcccf2679db
      Description: ''
      Environment:
        Variables:
          dynamoDbTable: dev-ProcessingArchive
          s3bucket: dev-processarchive-113jfdk89
      FunctionName: DEV-ExtractMeta
      Handler: index.handler
      MemorySize: 1536
      Role: arn:aws:iam::970386504547:role/Processor
      Runtime: nodejs4.3
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
