version: 0.1

environment_variables:
  plaintext:
            
phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files: 
    - '**/*'
  base-directory: 'src/main/js/capturendcorrelate'
