AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  InvokeImgStepFunction:
    Properties:
      CodeUri: s3://proceso-deployments-8927459/52bb606c50799daf3dd3d48e02f817a5
      Description: ''
      Environment:
        Variables:
          stateMachineArn: arn:aws:states:us-west-2:970386504547:stateMachine:ImageProcStateMachine-MWZYPTDOWJHH
      FunctionName: InvokeImgStepFunction
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::970386504547:role/Processor
      Runtime: nodejs4.3
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
